---
- name: Make tmp directory
  ansible.builtin.file:
    path: /tmp/openfaas
    mode: "0755"
    state: directory

- name: Download namespace manifest
  ansible.builtin.get_url:
    url: "{{ openfaas_github_raw_url }}/master/namespaces.yml"
    dest: /tmp/openfaas/namespace.yml
    mode: "0644"

- name: Create namespace
  kubernetes.core.k8s:
    state: present
    src: /tmp/openfaas/namespace.yml

- name: Add openfaas repository
  kubernetes.core.helm_repository:
    name: openfaas
    repo_url: https://openfaas.github.io/faas-netes/

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Deploy openfaas
  kubernetes.core.helm:
    name: "{{ openfaas_release_name }}"
    chart_ref: openfaas/openfaas
    release_namespace: "{{ openfaas_namespace }}"
    values:
      serviceType: "{{ openfaas_service_type }}"

- name: Delete tmp directory
  ansible.builtin.file:
    path: /tmp/openfaas
    state: absent
