---
- name: "Create {{ linkerd_work_dir }}"
  ansible.builtin.file:
    path: "{{ linkerd_work_dir }}"
    mode: "0755"
    state: directory

- name: Add linkerd repository
  kubernetes.core.helm_repository:
    name: linkerd
    repo_url: https://helm.linkerd.io/stable

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Install CRDs
  kubernetes.core.helm:
    name: "{{ linkerd_crd_release_name }}"
    chart_ref: linkerd/linkerd-crds
    release_namespace: "{{ linkerd_namespace }}"
    create_namespace: true

- name: Install linkerd CNI plugin
  kubernetes.core.helm:
    name: "{{ linkerd_cni_release_name }}"
    chart_ref: linkerd/linkerd2-cni
    release_namespace: "{{ linkerd_cni_namespace }}"
    create_namespace: true

- name: Generate own root certificates for mTLS
  block:
    - name: Delete previous certificates
      ansible.builtin.file:
        path: "{{ linkerd_work_dir }}/{{ item }}"
        state: absent
      loop:
        - ca.crt
        - ca.key
        - issuer.key
        - issuer.crt

    - name: Generate trust anchor certificate
      ansible.builtin.command: >
        step certificate create
        root.linkerd.cluster.local
        {{ linkerd_work_dir }}/ca.crt
        {{ linkerd_work_dir }}/ca.key
        --profile root-ca
        --no-password
        --insecure
        --not-after=87600h
      register: result
      changed_when: result.rc == 0

    - name: Generate issuer certificate and key
      ansible.builtin.command: >
        step certificate create
        identity.linkerd.cluster.local
        {{ linkerd_work_dir }}/issuer.crt
        {{ linkerd_work_dir }}/issuer.key
        --profile intermediate-ca
        --not-after 8760h
        --no-password
        --insecure
        --ca {{ linkerd_work_dir }}/ca.crt
        --ca-key {{ linkerd_work_dir }}/ca.key
      register: result
      changed_when: result.rc == 0

- name: Install linkerd control plane
  kubernetes.core.helm:
    name: "{{ linkerd_release_name }}"
    chart_ref: linkerd/linkerd-control-plane
    release_namespace: "{{ linkerd_namespace }}"
    create_namespace: true
    set_values:
      - value: "identityTrustAnchorsPEM={{ linkerd_work_dir }}/ca.crt"
        value_type: file
      - value: "identity.issuer.tls.crtPEM={{ linkerd_work_dir }}/issuer.crt"
        value_type: file
      - value: "identity.issuer.tls.keyPEM={{ linkerd_work_dir }}/issuer.key"
        value_type: file
      - value: cniEnabled=true
        value_type: raw

- name: Install linkerd-viz
  kubernetes.core.helm:
    name: "{{ linkerd_viz_release_name }}"
    chart_ref: linkerd/linkerd-viz
    release_namespace: "{{ linkerd_viz_namespace }}"
    create_namespace: true
    set_values:
      - value: "dashboard.enforcedHostRegexp={{ linkerd_viz_hostname }}"
        value_type: string
