---
- ansible.builtin.import_tasks: install.yml
  vars:
    architecture: "{{ architectures[ansible_facts.architecture] }}"
    node_shell: "{{ ansible_facts.user_shell }}"
    node_package_manager: "{{ ansible_facts.pkg_mgr }}"
