---
- name: Get cluster token and ca.crt hash
  hosts: controller
  gather_facts: true
  tasks:
    - name: Generate token
      command: kubeadm token create
      register: token

    - name: Get ca-cert-hash
      shell: >
        openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt |
        openssl rsa -pubin -outform der 2>/dev/null |
        openssl dgst -sha256 -hex | sed 's/^.* //'
      register: hash

- name: Add worker nodes to cluster
  hosts: worker
  gather_facts: false
  tasks:
    - name: "Start kubelet"
      systemd:
        name: kubelet
        state: started
        enabled: true
      become: true

    - name: Add worker node
      command: >
        kubeadm join {{ hostvars[controller].ansible_facts.eth0.ipv4.address }}:6443
        --discovery-token {{ hostvars[controller].token.stdout }}
        --discovery-token-ca-cert-hash sha256:{{ hostvars[controller].hash.stdout }}
      become: true
      vars:
        controller: "{{ groups.control_plane[0] }}"

- name: Delete the token
  hosts: controller
  gather_facts: false
  tasks:
    - name: Delete the token on controller
      command: "kubeadm token delete {{ hostvars[controller].token.stdout }}"
      changed_when: true
      vars:
        controller: "{{ groups.control_plane[0] }}"
