---
- name: Check ansible module
  ansible.builtin.import_playbook: playbooks/setup_module.yml
  tags: module

- name: Install components
  ansible.builtin.import_playbook: playbooks/setup_components.yml
  tags: components

- name: Create cluster
  ansible.builtin.import_playbook: playbooks/setup_cluster.yml
  tags: cluster
  when: not ha_cluster.enabled | bool

- name: Create HA cluster
  ansible.builtin.import_playbook: playbooks/setup_ha_cluster.yml
  tags: cluster
  when: ha_cluster.enabled | bool

- name: Add worker nodes
  ansible.builtin.import_playbook: playbooks/add_worker.yml
  tags: add_worker
  when:
    - not ha_cluster.enabled | bool
    - groups.worker | default([]) | length > 0

- name: Setup ingress controller
  ansible.builtin.import_playbook: playbooks/setup_ingress_controller.yml
  tags: ingress

- name: Setup openebs
  ansible.builtin.import_playbook: playbooks/setup_openebs.yml
  tags: openebs
  when: openebs_install | bool

- name: Setup longhorn
  ansible.builtin.import_playbook: playbooks/setup_longhorn.yml
  tags: longhorn
  when: longhorn_install | bool

- name: Setup argocd
  ansible.builtin.import_playbook: playbooks/setup_argocd.yml
  tags: argocd
  when: argocd_install | bool

- name: Setup tekton
  ansible.builtin.import_playbook: playbooks/setup_tekton.yml
  tags: tekton
  when: tekton_install | bool

- name: Setup harbor
  ansible.builtin.import_playbook: playbooks/setup_harbor.yml
  tags: harbor
  when:
    - harbor_install | bool
    - (action is undefined) or (action != "uninstall")

- name: Uninstall harbor
  ansible.builtin.import_playbook: playbooks/cleanup_harbor.yml
  tags: harbor
  when:
    - action is defined
    - action == "uninstall"

- name: Setup gitea
  ansible.builtin.import_playbook: playbooks/setup_gitea.yml
  tags: gitea
  when:
    - gitea_install | bool
    - (action is undefined) or (action != "uninstall")

- name: Uninstall gitea
  ansible.builtin.import_playbook: playbooks/cleanup_gitea.yml
  tags: gitea
  when:
    - action is defined
    - action == "uninstall"
