---
- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: true
  become: true

- name: Put kubeadm config file
  ansible.builtin.template:
    src: kubeadm_config_v1beta3.yml.j2
    dest: "{{ kubeadm_config_path }}"
    mode: "0755"
    lstrip_blocks: true

- name: Kubeadm init
  ansible.builtin.command: >
    kubeadm init --config {{ kubeadm_config_path }}
  changed_when: true
  become: true

- name: Create ~/.kube
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Delete previous config
  ansible.builtin.file:
    state: absent
    path: "/home/{{ ansible_user }}/.kube/config"

- name: Copy admin.conf to ~/.kube/config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true
  become: true
