---
- name: "Create {{ openebs_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ openebs_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add openebs repository
  kubernetes.core.helm_repository:
    name: openebs
    repo_url: https://openebs.github.io/charts

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Deploy openebs
  kubernetes.core.helm:
    name: "{{ openebs_release_name }}"
    chart_ref: openebs/openebs
    release_namespace: "{{ openebs_namespace }}"

- name: Set openebs provisioner as default storage class
  when: openebs_set_default_storage_class | bool
  block:
    - name: Wait until openebs provisioner is running
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ openebs_namespace }}"
        label_selectors:
          - app=openebs
          - component=localpv-provisioner
      register: result
      until: result.resources[0].status.phase == "Running"
      retries: 30
      delay: 5

    - name: Set openebs provisioner as default storage class
      kubernetes.core.k8s:
        kind: StorageClass
        name: openebs-hostpath
        namespace: "{{ openebs_namespace }}"
        state: patched
        definition:
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
