---
distribution: ubuntu
deb_architecture:
  aarch64: arm64
  x86_64: amd64

# Cert
registry_name: myregistry.domain
cacert_name: ca.crt
docker_cert_dir: /etc/docker/certs.d
docker_cert_src: "/tmp/{{ cacert_name }}"
docker_cert_dest: "{{ docker_cert_dir }}/{{ registry_name }}/{{ cacert_name }}"
