---
gitea_release_name: gitea
gitea_namespace: gitea
gitea_admin_username: gitea_admin
gitea_admin_password: "r8sA8CPHD9!bt6d"
gitea_admin_email: "gitea@local.domain"
gitea_config_server_domain: git.example.com

gitea_storage_class: ""
gitea_host_path_dir: /opt/kube/gitea

gitea_pv_enabled: true
gitea_pv:
  gitea:
    name: gitea
    storage: 1Gi
    label: gitea
    host_path: "{{ gitea_host_path_dir }}/gitea"
  postgresql:
    name: gitea-postgresql
    storage: 1Gi
    label: postgresql
    host_path: "{{ gitea_host_path_dir }}/postgresql"

gitea_pvc:
  gitea:
    name: data-gitea-0
    storage: "{{ gitea_pv.gitea.storage }}"
    label: "{{ gitea_pv.gitea.label }}"
    selector_label: "{{ gitea_pv.gitea.label }}"
  postgresql:
    name: data-gitea-postgresql-0
    storage: "{{ gitea_pv.postgresql.storage }}"
    label: "{{ gitea_pv.postgresql.label }}"
    selector_label: "{{ gitea_pv.postgresql.label }}"
