---
- name: "Create {{ longhorn_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ longhorn_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add longhorn repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Deploy longhorn
  kubernetes.core.helm:
    name: "{{ longhorn_release_name }}"
    chart_ref: longhorn/longhorn
    release_namespace: "{{ longhorn_namespace }}"

- name: Check if storage class exists
  kubernetes.core.k8s_info:
    name: longhorn
    kind: StorageClass
    namespace: "{{ longhorn_namespace }}"
  register: result

- name: Create storage class
  kubernetes.core.k8s:
    state: present
    template: storage_class.yml.j2
  when: result.resources | length == 0
