---
architecture: amd64
# architecture: arm64

containerd_version: 1.6.20
containerd_config: /etc/containerd/config.toml
containerd_release_url: https://github.com/containerd/containerd/releases/download

# runc
runc_version: 1.1.6
runc_release_url: https://github.com/opencontainers/runc/releases/download

# cni
cni_plugin_install_dir: /opt/cni/bin
cni_plugin_version: "1.2.0"
cni_plugin_repo_url: "https://github.com/containernetworking/plugins/releases/download"

# Cert
registry_name: myregistry.domain
cacert_name: ca.crt
containerd_cert_dir: /etc/containerd/certs.d
containerd_cert_src: "/tmp/{{ cacert_name }}"
containerd_cert_dest: "{{ containerd_cert_dir }}/{{ registry_name }}/{{ cacert_name }}"
