---
- name: Create temporary directory
  ansible.builtin.file:
    path: /tmp/velero
    state: directory
    mode: "0755"

- name: Install the latest CLI
  when: velero_cli_version == "latest"
  block:
    - name: Get the latest version
      ansible.builtin.import_role:
        name: github
      vars:
        organization: vmware-tanzu
        repository: velero
        query_string: velero

    - name: Install the latest CLI for amd64
      when: velero_cli_architecture == "amd64" or velero_cli_architecture == "x86_64"
      block:
        - name: Download
          ansible.builtin.get_url:
            url: "{{ velero_release_url }}/v{{ release_latest_version }}/velero-v{{ release_latest_version }}-linux-amd64.tar.gz"
            dest: /tmp/velero/velero-linux.tar.gz
            mode: "0644"
          become: true

        - name: Extract
          ansible.builtin.unarchive:
            src: /tmp/velero/velero-linux.tar.gz
            dest: /tmp/velero
            remote_src: true
          become: true

        - name: Put cli in PATH
          ansible.builtin.copy:
            src: "/tmp/velero/velero-v{{ release_latest_version }}-linux-amd64/velero"
            dest: /usr/local/bin/velero
            mode: "0755"
            remote_src: true
          become: true

    - name: Install the latest CLI for arm64
      when: velero_cli_architecture == "arm64" or velero_cli_architecture == "aarch64"
      block:
        - name: Download
          ansible.builtin.get_url:
            url: "{{ velero_release_url }}/v{{ release_latest_version }}/velero-v{{ release_latest_version }}-linux-arm64.tar.gz"
            dest: /tmp/velero/velero-linux.tar.gz
            mode: "0644"
          become: true

        - name: Extract
          ansible.builtin.unarchive:
            src: /tmp/velero/velero-linux.tar.gz
            dest: /tmp/velero
            remote_src: true
          become: true

        - name: Put cli in PATH
          ansible.builtin.copy:
            src: "/tmp/velero/velero-v{{ release_latest_version }}-linux-arm64/velero"
            dest: /usr/local/bin/velero
            mode: "0755"
            remote_src: true
          become: true

- name: "Install the {{ velero_cli_version }} CLI"
  when: velero_cli_version != "latest"
  block:
    - name: Install the latest CLI for amd64
      when: velero_cli_architecture == "amd64" or velero_cli_architecture == "x86_64"
      block:
        - name: Download
          ansible.builtin.get_url:
            url: "{{ velero_release_url }}/v{{ velero_cli_version }}/velero-v{{ velero_cli_version }}-linux-amd64.tar.gz"
            dest: /tmp/velero/velero-linux.tar.gz
            mode: "0644"
          become: true

        - name: Extract
          ansible.builtin.unarchive:
            src: "/tmp/velero/velero-linux.tar.gz"
            dest: /tmp/velero
            remote_src: true
          become: true

        - name: Put cli in PATH
          ansible.builtin.copy:
            src: "/tmp/velero/velero-v{{ velero_cli_version }}-linux-amd64/velero"
            dest: /usr/local/bin/velero
            mode: "0755"
            remote_src: true
          become: true

    - name: Install the latest CLI for arm64
      when: velero_cli_architecture == "arm64" or velero_cli_architecture == "aarch64"
      block:
        - name: Download
          ansible.builtin.get_url:
            url: "{{ velero_release_url }}/v{{ velero_cli_version }}/velero-v{{ velero_cli_version }}-linux-arm64.tar.gz"
            dest: /tmp/velero/velero-linux.tar.gz
            mode: "0644"
          become: true

        - name: Extract
          ansible.builtin.unarchive:
            src: "/tmp/velero/velero-linux.tar.gz"
            dest: /tmp/velero
            remote_src: true
          become: true

        - name: Put cli in PATH
          ansible.builtin.copy:
            src: "/tmp/velero/velero-v{{ velero_cli_version }}-linux-arm64/velero"
            dest: /usr/local/bin/velero
            mode: "0755"
            remote_src: true
          become: true
