---
- name: "Create {{ gitea_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ gitea_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add gitea repository
  kubernetes.core.helm_repository:
    name: gitea
    repo_url: https://dl.gitea.io/charts/

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Deploy gitea
  kubernetes.core.helm:
    name: "{{ gitea_release_name }}"
    chart_ref: gitea/gitea
    release_namespace: "{{ gitea_namespace }}"
    values:
      gitea:
        admin:
          username: "{{ gitea_admin_username }}"
          password: "{{ gitea_admin_password }}"
          email: "{{ gitea_admin_email }}"
        config:
          server:
            DOMAIN: "{{ gitea_config_server_domain }}"
      persistence:
        enabled: true
        existingClaim: "{{ gitea_pvc.gitea.name }}"
      postgresql:
        persistence:
          enabled: true
          existingClaim: "{{ gitea_pvc.postgresql.name }}"
        volumePermissions:
          enabled: true
