---
- name: "Create {{ gitea_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ gitea_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create persistentVolume
  kubernetes.core.k8s:
    state: present
    template: pv.yml.j2
    namespace: "{{ gitea_namespace }}"

- name: Create persistentVolumeClaim
  kubernetes.core.k8s:
    state: present
    template: pvc.yml.j2
    namespace: "{{ gitea_namespace }}"
