---
- name: "Add alias in {{ k8s_alias_path }}"
  ansible.builtin.blockinfile:
    dest: "{{ k8s_alias_path }}"
    block: |
      alias ns="kubens"
      alias ctx="kubectx"
    state: present
    marker: "# -- {mark} inserted by kubectx ansible task --"
    insertafter: '# -- BEGIN inserted by kubectx ansible task --'
