---
- name: Git clone kubectx
  ansible.builtin.git:
    repo: https://github.com/ahmetb/kubectx
    dest: /opt/kubectx
    depth: 1
    version: master
  become: true

- name: "Make symlink"
  ansible.builtin.file:
    src: "/opt/kubectx/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  become: true
  loop:
    - kubectx
    - kubens
