---
- name: Add kubernetes repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: true
    gpgcheck: true
    gpgkey: >
      https://packages.cloud.google.com/yum/doc/yum-key.gpg
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  become: true

- name: Install the latest kubernetes commands
  ansible.builtin.dnf:
    name:
      - kubectl
      - kubelet
      - kubeadm
    state: present
  become: true
  when: kubernetes_version == "latest"

- name: "Install kubernetes commands version {{ kubernetes_version }}"
  ansible.builtin.dnf:
    name:
      - "kubectl={{ kubernetes_version }}"
      - "kubelet={{ kubernetes_version }}"
      - "kubeadm={{ kubernetes_version }}"
    state: present
  become: true
  when: kubernetes_version != "latest"
