---
- name: Check distribution
  set_fact:
    distribution: "{{ ansible_facts.distribution | lower }}"
    family: "{{ ansible_facts.distribution_file_variety | lower }}"

- name: Install kubernetes for rhel-like
  import_tasks: install_rhel.yml
  when: family == "redhat"

- name: Install kubernetes for other distro
  import_tasks: "install_{{ distribution }}.yml"
  when: family != "redhat"
