---
- name: Create temporary directory
  ansible.builtin.file:
    path: /tmp/jaeger
    mode: "0755"
    state: directory

- name: Create namespace
  kubernetes.core.k8s:
    name: "{{ jaeger_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Download manifest
  ansible.builtin.get_url:
    url: "{{ jaeger_release_url }}/v{{ jaeger_version }}/jaeger-operator.yaml"
    mode: "0644"
    dest: /tmp/jaeger/jaeger-operator.yaml

- name: Check cert-manager webhook is running
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: cert-manager
    label_selectors:
      - "app=webhook"
      - "app.kubernetes.io/component=webhook"
      - "app.kubernetes.io/instance=cert-manager"
  register: result
  until: result.resources[0].status.phase == "Running"
  retries: 30
  delay: 5

- name: Apply manifest
  kubernetes.core.k8s:
    src: /tmp/jaeger/jaeger-operator.yaml
    state: present

- name: Wait until the operator pod is running
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ jaeger_namespace }}"
    label_selectors:
      - "name=jaeger-operator"
  register: result
  until: result.resources[0].status.phase == "Running"
  retries: 30
  delay: 5

# Wait 10 sec to avoid internal service error when post simplest.yml
- name: Wait 10 sec
  ansible.builtin.wait_for:
    timeout: 10
  delegate_to: localhost

- name: Put simplest.yml
  ansible.builtin.copy:
    src: simplest.yml
    mode: "0644"
    dest: /tmp/jaeger/simplest.yml

- name: Apply simplest.yml
  kubernetes.core.k8s:
    src: /tmp/jaeger/simplest.yml
    state: present
    namespace: "{{ jaeger_namespace }}"
