---
- name: Install calico
  when: calico_version == "latest"
  block:
    - name: Get the latest version
      ansible.builtin.import_role:
        name: github
      vars:
        organization: "{{ calico_organization }}"
        repository: "{{ calico_repository }}"
        query_string: 'tigera-operator'

    - name: Set version
      ansible.builtin.set_fact:
        calico_version: "{{ release_latest_version }}"

- name: Download Tigera Calico operator
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/{{ calico_organization }}/{{ calico_repository }}/v{{ calico_version }}//manifests/tigera-operator.yaml"
    dest: /tmp/calico-tigera-operator.yml
    mode: "0644"

- name: Deploy Tigera Calico operator
  kubernetes.core.k8s:
    state: present
    src: /tmp/calico-tigera-operator.yml

- name: Download Calico resources
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/{{ calico_organization }}/{{ calico_repository }}/v{{ calico_version }}//manifests/custom-resources.yaml"
    dest: /tmp/calico-custom-resources.yml
    mode: "0644"

- name: Update network cidr
  ansible.builtin.replace:
    path: /tmp/calico-custom-resources.yml
    regexp: '^(\s+)cidr: (.*)$'
    replace: '\1cidr: {{ calico_network_cidr }}'

- name: Deploy Calico resources
  kubernetes.core.k8s:
    state: present
    src: /tmp/calico-custom-resources.yml
