---
- name: Put example app manifest
  ansible.builtin.template:
    src: example_app.yml.j2
    dest: /tmp/example_app.yml
    mode: "0644"

- name: Delete example app from a cluster
  kubernetes.core.k8s:
    state: absent
    src: /tmp/example_app.yml"
    namespace: default
