---
- name: Zsh completion
  when: shell == "zsh"
  block:
    - name: Check ~/.zshrc exist
      ansible.builtin.stat:
        path: ~/.zshrc
      register: result

    - name: "Add completion in {{ k8s_plugin_setting_path }}"
      ansible.builtin.blockinfile:
        dest: "{{ k8s_plugin_setting_path }}"
        block: source <(stern --completion=zsh)
        state: present
        marker: "# -- {mark} inserted by stern ansible task --"
        insertafter: '# -- BEGIN inserted by stern ansible task --'
      when: result.stat.exists
