---
- name: Install stern
  ansible.builtin.command:
    argv:
      - ~/.krew/bin/kubectl-krew
      - install
      - stern
  register: result
  failed_when: result.rc != 0
  changed_when: result.rc == 0
