---
- name: Uninstall previous docker version
  ansible.builtin.dnf:
    name:
      - podman-docker
    state: absent
  become: true

- name: Add docker repository
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
  become: true

- name: Install podman docker
  ansible.builtin.dnf:
    name:
      - podman-docker
    state: present
  become: true

- name: Enable podman serveice
  ansible.builtin.systemd:
    name: podman
    state: started
    enabled: true
  become: true
