---
- name: Uninstall previous docker version
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: true

- name: Apt update
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Apt install packages necessary for docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: true

- name: Add docker GPG key
  become: true
  block:
    - name: mkdir /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        owner: root
        group: root
        mode: "0755"
        state: directory
        recurse: true

    - name: Remove old gpg key
      ansible.builtin.file:
        path: "/etc/apt/keyrings/{{ item }}"
        state: absent
      loop:
        - docker.gpg
        - docker.gpg.tmp
      become: true

    - name: Download gpg key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg.tmp
        mode: "0644"
      become: true

    - name: Dearmor gpg key
      ansible.builtin.command: |
        sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.gpg.tmp
      changed_when: true
      become: true

    - name: Remove tmp gpg key
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg.tmp
        state: absent
      become: true

- name: Set node architecture
  ansible.builtin.set_fact:
    arch: "{{ [ansible_architecture] | map('extract', deb_architecture) | first }}"
    codename: "{{ ansible_facts.lsb.codename }}"

- name: Set up docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/{{ distribution }}
      {{ codename }} stable
    state: present
    filename: docker
  become: true

- name: Apt update
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: true

- name: Enable docker serveice
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true
