---
- name: Uninstall previous docker version
  ansible.builtin.yum:
    name:
      - docker
      - containerd
      - runc
    state: absent
  become: true

- name: Install docker
  ansible.builtin.yum:
    name:
      - docker
      - containerd
      - runc
    state: present
  become: true

- name: Enable docker serveice
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true
