---
- name: Check distribution
  ansible.builtin.set_fact:
    distribution: "{{ ansible_facts.distribution | lower }}"
    family: "{{ ansible_facts.distribution_file_variety | lower }}"

- name: Install docker for rhel-like
  ansible.builtin.import_tasks: install_rhel.yml
  when: family == "redhat"

- name: Install docker for other distro
  ansible.builtin.import_tasks: "install_{{ distribution }}.yml"
  when: family != "redhat"
