---
- name: "Create {{ traefik_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ traefik_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add traefik repository
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Deploy traefik
  kubernetes.core.helm:
    name: "{{ traefik_release_name }}"
    chart_ref: traefik/traefik
    release_namespace: "{{ traefik_namespace }}"
    values: "{{ traefik_values }}"
