---
- name: Install tekton CLI
  ansible.builtin.dnf:
    name: "{{ tekton_release_url }}/v{{ tekton_cli_version }}/tektoncd-cli-{{ tekton_cli_version }}_Linux-64bit.rpm"
    state: present
    disable_gpg_check: true
  become: true
