---
- name: Make working directory
  ansible.builtin.file:
    path: "{{ working }}"
    state: directory
    mode: "0755"

- name: Download tekton component manifests
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/tekton-releases/{{ item.name }}"
    dest: "{{ working }}/{{ item.dest }}"
    mode: "0644"
  loop:
    - name: pipeline/latest/release.yaml
      dest: pipeline.yml
    - name: dashboard/latest/release.yaml
      dest: dashboard.yml
    - name: triggers/latest/release.yaml
      dest: triggers.yml
    - name: triggers/latest/interceptors.yaml
      dest: interceptors.yml

- name: Deploy tekton pipeline and dashboard
  kubernetes.core.k8s:
    src: "{{ working }}/{{ item }}"
    state: present
    namespace: "{{ tekton_namespace }}"
  loop:
    - pipeline.yml
    - dashboard.yml

# - name: Delete ValidatingWebhookConfiguration for installing triggers
#   kubernetes.core.k8s:
#     state: absent
#     api_version: v1
#     kind: ValidatingWebhookConfiguration
#     name: config.webhook.pipeline.tekton.dev
#     namespace: "{{ tekton_namespace }}"
#   register: result
#   until: not result.failed
#   retries: 10
#   delay: 5

# - name: Deploy tekton triggers
#   kubernetes.core.k8s:
#     src: "{{ working }}/triggers.yml"
#     state: present
#     namespace: "{{ tekton_namespace }}"
#   register: result
#   until: not result.failed
#   retries: 10
#   delay: 5

# - name: Deploy interceptors
#   ansible.builtin.command: |
#     kubectl apply -f {{ working }}/interceptors.yml -n {{ tekton_namespace }}
#   register: result
#   until: result.rc == 0
#   retries: 5
#   delay: 5

# - name: Add ValidatingWebhookConfiguration
#   ansible.builtin.command: |
#     kubectl apply -f {{ working }}/pipeline.yml -n {{ tekton_namespace }}
#   register: result
#   until: result.rc == 0 or result.rc == 1
#   retries: 5
#   delay: 5

- name: Delete working directory
  ansible.builtin.file:
    path: "{{ working }}"
    state: absent
