---
- name: "Create {{ kube_prometheus_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ kube_prometheus_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add kube_prometheus repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Deploy kube_prometheus
  kubernetes.core.helm:
    name: "{{ kube_prometheus_release_name }}"
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ kube_prometheus_namespace }}"
