---
- name: Add harbor repository
  kubernetes.core.helm_repository:
    name: harbor
    repo_url: https://helm.goharbor.io

- name: "Create {{ harbor_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ harbor_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Put values.yml on target node
  ansible.builtin.template:
    src: values.yml.j2
    dest: /tmp/values.yml
    mode: "0644"

- name: Deploy harbor
  kubernetes.core.helm:
    name: "{{ harbor_release_name }}"
    chart_ref: harbor/harbor
    namespace: "{{ harbor_namespace }}"
    values_files: /tmp/values.yml

- name: Delete values.yml on target node
  ansible.builtin.file:
    state: absent
    path: /tmp/values.yml
  become: true
