---
- name: Make directory on node for host path
  ansible.builtin.file:
    state: directory
    path: "{{ item.value.host_path }}"
    mode: "0777"
  become: true
  loop: "{{ harbor_pv | dict2items }}"
  when: harbor_pv_enabled | bool
