---
- name: "Create {{ harbor_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ harbor_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create persistentVolume
  kubernetes.core.k8s:
    state: present
    template: pv.yml.j2
    namespace: "{{ harbor_namespace }}"
  when: harbor_pv_enabled | bool

- name: Create persistentVolumeClaim
  kubernetes.core.k8s:
    state: present
    template: pvc.yml.j2
    namespace: "{{ harbor_namespace }}"
