---
- name: Get cluster token and ca.crt hash
  hosts: control_node
  gather_facts: true
  tasks:
    - name: Generate token
      ansible.builtin.command: kubeadm token create
      register: token
      changed_when: true

    - name: Get ca-cert-hash
      ansible.builtin.shell: >
        set -o pipefail &&
        openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt |
        openssl rsa -pubin -outform der 2>/dev/null |
        openssl dgst -sha256 -hex | sed 's/^.* //'
      register: hash
      changed_when: false
      args:
        executable: /bin/bash

- name: Add worker nodes to cluster
  hosts: worker
  gather_facts: false
  tasks:
    - name: "Start kubelet"
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: true
      become: true

    - name: Add worker node
      ansible.builtin.command: >
        kubeadm join {{ hostvars[control_node].ansible_facts.default_ipv4.address }}:6443
        --discovery-token {{ hostvars[control_node].token.stdout }}
        --discovery-token-ca-cert-hash sha256:{{ hostvars[control_node].hash.stdout }}
      become: true
      vars:
        control_node: "{{ groups.control_plane[0] }}"
      changed_when: true

- name: Delete the token
  hosts: control_node
  gather_facts: false
  tasks:
    - name: Delete the token on control_node
      ansible.builtin.command: "kubeadm token delete {{ hostvars[control_node].token.stdout }}"
      changed_when: true
      vars:
        control_node: "{{ groups.control_plane[0] }}"
