---
- name: Clean up on worker nodes
  hosts: worker
  gather_facts: false
  tasks:
    - name: Clean up node
      ansible.builtin.command: kubeadm reset --force
      changed_when: true
      become: true

    - name: Remove /etc/cni/net.d
      ansible.builtin.file:
        path: /etc/cni/net.d
        state: absent
      become: true

    - name: Delete flannel interface
      ansible.builtin.command: ip link delete flannel.1
      changed_when: true
      become: true
      register: delete_result
      failed_when: delete_result.rc != 0 and delete_result.rc != 1

- name: Clean up on control_plane
  hosts: control_plane
  gather_facts: false
  tasks:
    - name: Clean up control plane
      ansible.builtin.command: kubeadm reset --force
      changed_when: true
      become: true

    - name: Delete flannel interface
      ansible.builtin.command: ip link delete flannel.1
      changed_when: true
      become: true
      register: delete_result
      failed_when: delete_result.rc != 0 and delete_result.rc != 1
