---
- name: Uninstall gitea
  hosts: control_node
  gather_facts: false
  tasks:
    - name: Uninstall gitea
      ansible.builtin.import_role:
        name: gitea
        tasks_from: uninstall

    - name: Delete persistentVolume and persistentVolumeClaim
      ansible.builtin.import_role:
        name: gitea
        tasks_from: delete_pv

- name: Delete host path
  hosts: all
  gather_facts: false
  tasks:
    - name: Delete host path
      ansible.builtin.import_role:
        name: gitea
        tasks_from: delete_hostpath
