---
- name: Uninstall gitea
  hosts: controller
  gather_facts: false
  tasks:
    - name: Uninstall gitea
      ansible.builtin.import_role:
        name: gitea
        tasks_from: uninstall

- name: Delete persistentVolume and persistentVolumeClaim
  hosts: all
  gather_facts: false
  tasks:
    - name: Delete pv and pvc
      ansible.builtin.import_role:
        name: gitea
        tasks_from: delete_pv
