---
- name: Deploy nignx ingress control_node
  hosts: control_node
  gather_facts: false
  tasks:
    - name: Deploy
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: deploy_ingress
