---
- name: Deploy awx
  hosts: control_plane[0]
  gather_facts: false
  tasks:
    - name: Deploy awx
      ansible.builtin.import_role:
        name: awx

- name: Install cli
  hosts: control_plane
  gather_facts: true
  tasks:
    - name: Install cli
      ansible.builtin.import_role:
        name: awx
        tasks_from: cli
