---
- name: Install dependencies
  hosts: all
  gather_facts: true
  tasks:
    - name: Install dependencies
      ansible.builtin.import_role:
        name: openebs
        tasks_from: dependencies
      vars:
        architecture: "{{ ansible_facts.architecture }}"
        package_manager: "{{ ansible_facts.pkg_mgr }}"

- name: Deploy openebs
  hosts: control_node
  gather_facts: false
  roles:
    - role: openebs
