---
- name: Deploy openfaas
  hosts: control_plane[0]
  gather_facts: false
  tasks:
    - name: Deploy openfaas
      ansible.builtin.import_role:
        name: openfaas

- name: Install cli
  hosts: control_plane
  gather_facts: true
  tasks:
    - name: Install cli
      ansible.builtin.import_role:
        name: openfaas
        tasks_from: cli
