---
- name: Install components on compute instances
  hosts: all
  gather_facts: true
  roles:
    - role: docker
      tags: docker

    - role: kubernetes
      tags: kubernetes

    - role: containerd
      tags: containerd

    - role: helm
      tags: helm
