---
- name: Install CRI
  hosts: all
  gather_facts: true
  tasks:
    - name: sysctl settings
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: sysctl

- name: Setup kubernetes cluster with kubeadm
  hosts: control_node
  gather_facts: true
  tasks:
    - name: Kubeadm init
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: kubeadm_init
      vars:
        ipv4_address: "{{ ansible_facts.default_ipv4.address }}"

    - name: Install CNI
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: deploy_cni

    - name: Taint control plane nodes
      ansible.builtin.command: |
        kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      changed_when: true
      when: taint_control_plane_node | bool

    - name: Check python and pip is installed
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: check_python