---
- name: Install cli
  hosts: control_plane
  gather_facts: true
  tasks:
    - name: Install cli
      ansible.builtin.import_role:
        name: velero
        tasks_from: cli
      vars:
        velero_cli_architecture: "{{ ansible_facts.architecture }}"

- name: Deploy velero
  hosts: control_plane[0]
  gather_facts: false
  tasks:
    - name: Deploy velero
      ansible.builtin.import_role:
        name: velero
