---
- name: Install CRI
  hosts: all
  gather_facts: true
  tasks:
    - name: Precheck
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: precheck

    - name: Common settings
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: common_settings

- name: Setup kubernetes cluster with kubeadm
  hosts: controller
  gather_facts: false
  tasks:
    - name: Kubeadm init
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: kubeadm_init

    - name: Install CNI
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: deploy_cni
