---
- name: Load module and set IP forwarding
  hosts: cluster
  gather_facts: true
  tasks:
    - name: Set sysctl
      ansible.builtin.import_role:
        name: cluster
        tasks_from: sysctl

    - name: Check resolv.conf
      ansible.builtin.import_role:
        name: kubelet
        tasks_from: resolv

- name: Setup kubernetes cluster with kubeadm
  hosts: control_plane[0]
  gather_facts: true
  tasks:
    - name: Kubeadm init
      ansible.builtin.import_role:
        name: kubeadm
        tasks_from: init
      vars:
        ipv4_address: "{{ ansible_facts.default_ipv4.address }}"

    - name: Install CNI
      ansible.builtin.include_role:
        name: "{{ cni_type }}"

    - name: Taint control plane nodes
      ansible.builtin.command: |
        kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      changed_when: true
      when: taint_control_plane_node | bool
