---
- name: Install longhorn dependencies
  hosts: all
  gather_facts: true
  tasks:
    - name: Install dependencies
      ansible.builtin.import_role:
        name: longhorn
        tasks_from: dependencies
      vars:
        architecture: ansible_facts.architecture
        package_manager: "{{ ansible_facts.pkg_mgr }}"

- name: Deploy longhorn
  hosts: controller
  gather_facts: false
  roles:
    - role: longhorn
