---
- name: Install components on compute instances
  hosts: all
  gather_facts: true
  roles:
    - role: kubernetes
      tags: kubernetes

    - role: containerd
      tags: containerd
      vars:
        architecture: "{{ ansible_facts.architecture }}"

    - role: nerdctl
      tags: nerdctl

    - role: helm
      tags: helm
