---
- name: Deploy tekton components
  hosts: control_plane[0]
  gather_facts: false
  roles:
    - role: tekton
      tags: tekton

- name: Install tekton cli
  hosts: cluster
  gather_facts: true
  tasks:
    - name: Install cli
      ansible.builtin.import_role:
        name: tekton
        tasks_from: cli
      vars:
        package_manager: "{{ ansible_facts.pkg_mgr }}"
        architecture: "{{ architectures[ansible_facts.architecture] }}"
