---
- name: Deploy nignx ingress controller
  hosts: controller
  gather_facts: false
  tasks:
    - name: Deploy
      ansible.builtin.import_role:
        name: setup_cluster
        tasks_from: deploy_ingress
