---
- name: "Create {{ kubevious_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ kubevious_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add kubevious repository
  kubernetes.core.helm_repository:
    name: kubevious
    repo_url: https://helm.kubevious.io

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Put values.yml on target node
  ansible.builtin.template:
    src: values.yml.j2
    dest: /tmp/values.yml
    mode: "0644"

- name: Deploy kubevious
  kubernetes.core.helm:
    name: "{{ kubevious_release_name }}"
    chart_ref: kubevious/kubevious
    release_namespace: "{{ kubevious_namespace }}"
    values_files: /tmp/values.yml

- name: Delete values.yml on target node
  ansible.builtin.file:
    state: absent
    path: /tmp/values.yml
  become: true
