---
name: Check codes by linter

on:
  push:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    name: Code check
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ansible-lint
        run: pip install ansible-lint

      # - name: Run ansible-lint
      #   run: ansible-lint -vv
