---
name: Check codes by linter

on:
  push:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    name: Code check
    steps:
      - uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible-lint -vv
