---
name: Stop EC2 instances

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      EC2_CONTROLLER_TAG:
        required: true
      EC2_WORKER1_TAG:
        required: true

jobs:
  stop_ec2:
    runs-on: ubuntu-latest
    name: Stop EC2 instances
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Stop ec2
        run: |
          controller=$(testdata/aws_instance_id.sh ${{ secrets.EC2_CONTROLLER_TAG }})
          worker1=$(testdata/aws_instance_id.sh ${{ secrets.EC2_WORKER1_TAG }})
          aws ec2 stop-instances --instance-ids ${controller} > /dev/null
          aws ec2 stop-instances --instance-ids ${worker1} > /dev/null
