---
- name: Add repository
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
  become: true

- name: Install the latest containerd
  ansible.builtin.dnf:
    name: containerd.io
    state: present
    allowerasing: true
  become: true
  when: containerd_version == "latest"

- name: "Install containerd version containerd_version"
  ansible.builtin.dnf:
    name: "containerd.io={{ containerd_version }}"
    state: present
    allow_downgrade: true
    allowerasing: true
  become: true
  when: containerd_version != "latest"

- name: Put /etc/containerd/config.toml
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
