---
- name: Make working directory
  ansible.builtin.file:
    path: "{{ working }}"
    state: directory
    mode: "0755"

- name: Put example app manifest
  ansible.builtin.template:
    src: example_nginx.yml.j2
    dest: "{{ working }}/example_nginx.yml"
    mode: "0644"

- name: Deploy example app
  kubernetes.core.k8s:
    state: present
    src: "{{ working }}/example_nginx.yml"
    namespace: default
  when: example_app_state == "present"

- name: Delete example app from a cluster
  kubernetes.core.k8s:
    state: absent
    src: "{{ working }}/example_nginx.yml"
    namespace: default
  when: example_app_state == "absent"

- name: Delete working directory
  ansible.builtin.file:
    path: "{{ working }}"
    state: absent
