---
- name: Install python3.9 and pip
  ansible.builtin.dnf:
    name:
      - python39
      - python39-pip
    state: present
  become: true

- name: Install python dependencies
  ansible.builtin.pip:
    name:
      - kubernetes >= 12.0.0
      - pyyaml >= 3.11
      - jsonpatch
    state: present
    extra_args: --user
    executable: pip3.9
