---
- name: Disable swap
  command: swapoff -a
  changed_when: true

- name: kubeadm init
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
  changed_when: true
  become: true

- name: Create ~/.kube
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy admin.conf to ~/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true
  become: true
